[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info

[program:channel1]
command=/encoder/encode-channel.sh 1
environment=INPUT_TYPE="%(ENV_INPUT_TYPE)s",ICECAST_HOST="%(ENV_ICECAST_HOST)s",ICECAST_PORT="%(ENV_ICECAST_PORT)s",ICECAST_SOURCE_PASS="%(ENV_ICECAST_SOURCE_PASS)s",AUDIO_BITRATE="%(ENV_AUDIO_BITRATE)s"
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/var/log/supervisor/channel1.log
stderr_logfile=/var/log/supervisor/channel1.err
priority=10

[program:channel2]
command=/encoder/encode-channel.sh 2
environment=INPUT_TYPE="%(ENV_INPUT_TYPE)s",ICECAST_HOST="%(ENV_ICECAST_HOST)s",ICECAST_PORT="%(ENV_ICECAST_PORT)s",ICECAST_SOURCE_PASS="%(ENV_ICECAST_SOURCE_PASS)s",AUDIO_BITRATE="%(ENV_AUDIO_BITRATE)s"
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/var/log/supervisor/channel2.log
stderr_logfile=/var/log/supervisor/channel2.err
priority=20

[program:channel3]
command=/encoder/encode-channel.sh 3
environment=INPUT_TYPE="%(ENV_INPUT_TYPE)s",ICECAST_HOST="%(ENV_ICECAST_HOST)s",ICECAST_PORT="%(ENV_ICECAST_PORT)s",ICECAST_SOURCE_PASS="%(ENV_ICECAST_SOURCE_PASS)s",AUDIO_BITRATE="%(ENV_AUDIO_BITRATE)s"
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/var/log/supervisor/channel3.log
stderr_logfile=/var/log/supervisor/channel3.err
priority=30

[program:channel4]
command=/encoder/encode-channel.sh 4
environment=INPUT_TYPE="%(ENV_INPUT_TYPE)s",ICECAST_HOST="%(ENV_ICECAST_HOST)s",ICECAST_PORT="%(ENV_ICECAST_PORT)s",ICECAST_SOURCE_PASS="%(ENV_ICECAST_SOURCE_PASS)s",AUDIO_BITRATE="%(ENV_AUDIO_BITRATE)s"
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/var/log/supervisor/channel4.log
stderr_logfile=/var/log/supervisor/channel4.err
priority=40
